version: '3'
services:
  web:
    restart: always
    build: .
    image: golos-ui
    command: bash -c "cd db && ../node_modules/.bin/sequelize db:migrate && cd .. && yarn run production"

    environment:
      SDC_TARANTOOL_HOSTNAME: datastore
      SDC_DATABASE_URL: mysql://golosdev:golosdev@db:3306/golosdev

      # Registrator
      SDC_REGISTRAR_ACCOUNT: ${SDC_REGISTRAR_ACCOUNT}
      #SDC_REGISTRAR_AMOUNT:  ${SDC_REGISTRAR_AMOUNT}
      SDC_REGISTRAR_SIGNINGKEY: ${SDC_REGISTRAR_SIGNINGKEY}
      SDC_GMAIL_SEND_USER: ${SDC_GMAIL_SEND_USER}
      SDC_GMAIL_SEND_PASS: ${SDC_GMAIL_SEND_PASS}

      # Nodes
      SDC_CLIENT_WEBSOCKET_URL: ${SDC_CLIENT_WEBSOCKET_URL}
      SDC_SERVER_WEBSOCKET_URL: ${SDC_SERVER_WEBSOCKET_URL}
    ports:
      - 127.0.0.1:8080:8080

    depends_on:
      - db

  db:
    restart: always
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'golosdev'
      MYSQL_USER: 'golosdev'
      MYSQL_PASSWORD: 'golosdev'
      MYSQL_ROOT_PASSWORD: 'golosdev'

    ports:
      - 3306:3306

    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro

  datafeed:
    image: golosnotify/datafeed
    restart: unless-stopped
    build:
      context: https://github.com/golos-blockchain/golosnotify.git
      dockerfile: Dockerfile-datafeed
    environment:
      NODE_URL: ${SDC_SERVER_WEBSOCKET_URL}
      TARANTOOL_HOST: datastore

    depends_on:
      - datastore
      - db

  datastore:
    image: golosnotify/datastore
    build:
      context: https://github.com/golos-blockchain/golosnotify.git
      dockerfile: Dockerfile-datastore
    volumes:
      - ./data/tarantool:/var/lib/tarantool
    ports:
      - 127.0.0.1:3001:3001
